import {
  FiBriefcase,
  FiCode,
  FiLayers,
  FiUsers,
  FiAward,
  FiFileText,
  FiCpu,
  FiDatabase,
  FiSmartphone,
  FiTool,
  FiZap,
  FiPenTool,
  FiServer,
  FiGithub,
  FiLinkedin,
  FiInstagram,
  FiYoutube,
  FiTwitter,
  FiMail,
  FiPhone,
  FiMapPin,
  FiGlobe,
  FiStar,
  FiBookOpen,
  FiCamera,
  FiHeadphones,
  FiCompass,
  FiTarget,
} from "react-icons/fi";
import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiPrisma,
  SiPostgresql,
  SiMongodb,
  SiGit,
  SiPostman,
  SiArcgis,
  SiSocketdotio,
  SiVite,
  SiMongoose,
  SiJsonwebtokens,
  SiResend,
} from "react-icons/si";
import type { IconType } from "react-icons";

export const iconMap: Record<string, IconType> = {
  // Feather icons (general purpose)
  briefcase: FiBriefcase,
  code: FiCode,
  layers: FiLayers,
  users: FiUsers,
  award: FiAward,
  "file-text": FiFileText,
  cpu: FiCpu,
  database: FiDatabase,
  smartphone: FiSmartphone,
  tool: FiTool,
  zap: FiZap,
  "pen-tool": FiPenTool,
  server: FiServer,
  github: FiGithub,
  linkedin: FiLinkedin,
  instagram: FiInstagram,
  youtube: FiYoutube,
  twitter: FiTwitter,
  mail: FiMail,
  phone: FiPhone,
  "map-pin": FiMapPin,
  globe: FiGlobe,
  star: FiStar,
  "book-open": FiBookOpen,
  camera: FiCamera,
  headphones: FiHeadphones,
  compass: FiCompass,
  target: FiTarget,

  // Simple Icons (brand-specific icons)
  typescript: SiTypescript,
  javascript: SiJavascript,
  python: SiPython,
  react: SiReact,
  nextjs: SiNextdotjs,
  tailwindcss: SiTailwindcss,
  nodejs: SiNodedotjs,
  express: SiExpress,
  prisma: SiPrisma,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  git: SiGit,
  postman: SiPostman,
  arcgis: SiArcgis,
  socketio: SiSocketdotio,
  vite: SiVite,
  mongoose: SiMongoose,
  jwt: SiJsonwebtokens,
  resend: SiResend,
};

export function Icon({
  name,
  className,
  fallback = FiStar,
}: {
  name?: string | null;
  className?: string;
  fallback?: IconType;
}) {
  const Cmp = (name && iconMap[name]) || fallback;
  return <Cmp className={className} />;
}